"""create sponsor tables

Revision ID: e67a0a8f825d
Revises: 
Create Date: 2026-04-02 01:38:58.331606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e67a0a8f825d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_sponsors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_name', sa.Text(), nullable=False),
    sa.Column('route', sa.Text(), nullable=False),
    sa.Column('town_city', sa.Text(), nullable=True),
    sa.Column('county', sa.Text(), nullable=True),
    sa.Column('removed_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_name', 'route', name='uq_revoked_sponsor')
    )
    op.create_index(op.f('ix_revoked_sponsors_id'), 'revoked_sponsors', ['id'], unique=False)
    op.create_table('sponsors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_name', sa.Text(), nullable=False),
    sa.Column('town_city', sa.Text(), nullable=True),
    sa.Column('county', sa.Text(), nullable=True),
    sa.Column('type_rating', sa.Text(), nullable=True),
    sa.Column('route', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_name', 'route', name='uq_org_route')
    )
    op.create_index(op.f('ix_sponsors_id'), 'sponsors', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sponsors_id'), table_name='sponsors')
    op.drop_table('sponsors')
    op.drop_index(op.f('ix_revoked_sponsors_id'), table_name='revoked_sponsors')
    op.drop_table('revoked_sponsors')
    # ### end Alembic commands ###
